# Generated by Django 4.1 on 2023-01-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_rol',
            field=models.IntegerField(choices=[(1, 'Adminstrador'), (2, 'Vendedor'), (3, 'Comprador')], default=3),
        ),
    ]
